### ISSUE TITLE
Async validators

### ISSUE THREAD

**Issue by srph** [parris/iz#28]
Thinking of returning a promise from the provided `callback` argument provided to `addValidator`. For instance, a `unique` validator for usernames..

**Comment by xpepermint** [comment]
+1

**Comment by srph** [comment]
I can try to send a PR if the feature / idea is accepted.

**Comment by parris** [comment]
I mean this sounds awesome to me! +1

**Comment by srph** [comment]
Not sure which promise to use. We can use ES6 Promise so we can leave the option for the users to load the polyfill themselves.

**Comment by parris** [comment]
That sounds appropriate. It is an optional dependency that you can polyfill
with many libraries. How does the polyfill work server side?

**Comment by parris** [comment]
Looks like nodejs, iojs, and some shims support it
https://kangax.github.io/compat-table/es6/ .

A little more research showed that it might just be node 0.12. I think you
may still be able to shim some promise implementation globally if needed in
older versions. Some docs around that would be awesome.

Good call on es6!

**Comment by parris** [comment]
Note - I fix this in v2. Pull request is currently open. It did force me to rewrite a bunch of stuff.

**Comment by parris** [comment]
2 years later. This is fixed :).
