### ISSUE TITLE
email validation

### ISSUE THREAD

**Issue by jimmywarting** [parris/iz#31]
How is this valid?

```
var iz = require("iz")
iz("valid@email.com   foo").email().required().valid // true
```

https://tonicdev.com/56d7fb5074168d0d00297044/56d7fb5074168d0d00297045

**Comment by parris** [comment]
It's not. What's the likelihood users would type that though? Right now,
our email validation is stupid. It checks for an @ symbol. Submit a PR if
you have something better. My initial thought was i rather be more
permissive than too strict and block out things accidentally. The other
regexs out there are pretty unreadable. No one can tell if they are
accurate or not.

Proposal?

**Comment by parris** [comment]
Actually with exception of the multiple @ symbols that is a valid email.
Yea, let's get that part fixed.

**Comment by parris** [comment]
Fixed in v2. Also in previous versions you can addValidator to add a custom email address.
