### ISSUE TITLE
[feature request] Add MongoDB ObjectId validator

### ISSUE THREAD

**Issue by GauthamYerroju** [parris/iz#32]
Given that this can be useful with NodeJS, it would be great if there was a validator for MongoDB ObjectID:
https://docs.mongodb.org/manual/reference/method/ObjectId/

Great library by the way :+1:

**Comment by parris** [comment]
If you'd like to validate this you can use the `ofType` validator likely or create a custom validator using `addValidator`. We're trying to stay away from specific frameworks/dbs/etc.
