### ISSUE TITLE
yarn installation broken (invalid tar file)

### ISSUE THREAD

**Issue by KACAH** [parris/iz#35]
Hi! I get the following error while installing package via yarn (yarn add iz):

> error An unexpected error occurred: "https://registry.yarnpkg.com/iz/-/iz-2.1.2.tgz: invalid tar file".

Tested on clean project (yarn init, yarn add iz). As the yarn issue says (https://github.com/yarnpkg/yarn/issues/1619):

> Reporting as of May 14, 2017, that yarn publish seems to be borking things. npm publish works though 

So, looks like the solution is to bump the version and to republish iz with npm.

**Comment by parris** [comment]
Ahh geez, ok, let me try to fix this.

**Comment by parris** [comment]
Ok fixed up. Thanks for reporting. I tested it using yarn and npm. Let me know if anything seems "off".
