### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by jschill** [parris/iz#44]
Trying to run this with IE11, i think it fails on some ES proxy issue (im using https://github.com/GoogleChrome/proxy-polyfill).

Problem code:
https://github.com/parris/iz/blob/v2.2.2/src/are.js#L81

How that line looks compiled:
`currentIz = (_currentIz = currentIz)[rule.rule].apply(_currentIz, _toConsumableArray(args));`

Error message:
> Unhandled promise rejection TypeError: Unable to get property 'apply' of undefined or null reference

So, currentIz[rule.rule] is undefined. 

Would you recommend another proxy polyfill?

**Comment by parris** [comment]
Ahh thanks for this - I don't have another recommendation off the top of my head. However, perhaps we need to add another proxy trap for the 'apply' keyword within iz.

**Comment by parris** [comment]
Another option .... i think I can visualize a way to move away from the Proxy object again. We can then remove a requirement and make Iz more compatible with various platforms.

**Comment by parris** [comment]
Thanks for this - I'm investigating a way to solve this.

**Comment by parris** [comment]
@jschill I got a fix for you. Do you mind spot checking - https://github.com/parris/iz/pull/45

**Comment by parris** [comment]
I ended up merging and publishing. Let me know if you still have a problem. Closing this one out now.
