### ISSUE TITLE
Multiple doesn't handle floats correctly

### ISSUE THREAD

**Issue by LinusU** [parris/iz#46]
e.g.

```js
const iz = require('iz')
const validators = require('iz/lib/validators')

iz.register(validators)

console.log(iz(2.3).multiple(0.01).valid)
```

logs `false` instead of `true`.

This is because `2.3 % 0.01` is `0.009999999999999775` in JavaScript 🤦‍♂️

**Comment by parris** [comment]
Ahhh fun - sorry about that. Is there a validator you added manually as a workaround? Did you come up with a solution? Should we add that back into iz?

**Comment by LinusU** [comment]
I started exploring this due to mafintosh/is-my-json-valid#172. It seems like the implementation in is-my-json-valid works:

https://github.com/mafintosh/is-my-json-valid/blob/dcea5be83be29ea444c81bd83e7aef732a11c003/index.js#L100-L110

**Comment by parris** [comment]
@LinusU do I have permission to use that code in iz - with some tweaks and tests? Planning on making a new validator for multiples of floats.

**Comment by parris** [comment]
I'm going to assume the answer is yes :). Let me know if the implementation needs to be different.

**Comment by LinusU** [comment]
Absolutely, the code is MIT licensed!
